[project]
name = "Workshop_OpenSD2026"
version = "0.1.0"
description = "Repository containing the materials for the OpenSD2026 Workshop in Belgium"
readme = "README.md"
requires-python = ">=3.12,<3.13"
authors = [
    { name = "Yacine Bel-Hadj", email = "yacine.bel-hadj@vub.be" },
    { name = "Wout Weijtjens", email = "wout.weijtjens@vub.be" },
    { name = "Ahmed Mujtaba", email = "ahmed.mujtaba@vub.be" },
    { name = "Abdulelah Al-Ghuwaidi", email = "Abdulelah.Al-Ghuwaidi@vub.be" },
]
license-files = ["LICENSE"]

dependencies = [
    "h5py>=3.16.0",
    "ipykernel",
    "jupyterlab",
    "lightning>=2.6.5",
    "numpy>=2,<2.5",
    "pandas>=3.0.5",
    "polars>=1.44.0",
    "py-fatigue>=2",
    "pyoma-2",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "scipy",
    "torch",
    "zenodo-get>=3.1.0",
    "pytest",
    "pyarrow<25",
    "dynaresp>=0.5.1",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[dependency-groups]
dev = ["pytest"]

[tool.pytest.ini_options]
pythonpath = ["notebooks/WS1_An_intro_to_python/012_test_driven_dev",
]
testpaths = [
    "notebooks/WS1_An_intro_to_python/012_test_driven_dev/tests",
]
